id: P009392
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC356
  title: 'བསྟན་བཅོས་ཆེན་པོ་དབུ་མ་ལ་འཇུག་པའི་དགོངས་པ་རབ་ཏུ་གསལ་བར་བྱེད་པའི་དོགས་དཔྱོད་ལུང་རིགས་གཏེར་མཛོད། '
  author: ''
  volumes: {}
